config/routes.rb
Rails.application.routes.draw do
  resources :toys
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/toy.rb
class Toy < ApplicationRecord
    belongs_to :user11111
end

app/models/user11111.rb
class User11111 < ApplicationRecord
    has_many :toys, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  before_action :set_toy, only: [:show, :edit, :update, :destroy]

  # GET /toys
  # GET /toys.json
  def index
    @toys = Toy.all
  end

  # GET /toys/1
  # GET /toys/1.json
  def show
  end

  # GET /toys/new
  def new
    @toy = Toy.new
  end

  # GET /toys/1/edit
  def edit
  end

  # POST /toys
  # POST /toys.json
  def create
    @toy = Toy.new(toy_params)

    respond_to do |format|
      if @toy.save
        format.html { redirect_to @toy, notice: 'Toy was successfully created.' }
        format.json { render :show, status: :created, location: @toy }
      else
        format.html { render :new }
        format.json { render json: @toy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /toys/1
  # PATCH/PUT /toys/1.json
  def update
    respond_to do |format|
      if @toy.update(toy_params)
        format.html { redirect_to @toy, notice: 'Toy was successfully updated.' }
        format.json { render :show, status: :ok, location: @toy }
      else
        format.html { render :edit }
        format.json { render json: @toy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /toys/1
  # DELETE /toys/1.json
  def destroy
    @toy.destroy
    respond_to do |format|
      format.html { redirect_to toys_url, notice: 'Toy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_toy
      @toy = Toy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def toy_params
      params.require(:toy).permit(:name, :description, :date_posted, :posted_by)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/toys/_form.html.erb
<%= form_with(model: toy, local: true) do |form| %>
  <% if toy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(toy.errors.count, "error") %> prohibited this toy from being saved:</h2>

      <ul>
      <% toy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :date_posted %>
    <%= form.date_select :date_posted %>
  </div>

  <div class="field">
    <%= form.label :posted_by %>
    <%= form.text_field :posted_by %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/toys/edit.html.erb
<h1>Editing Toy</h1>

<%= render 'form', toy: @toy %>

<%= link_to 'Show', @toy %> |
<%= link_to 'Back', toys_path %>

app/views/toys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Toys</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Date posted</th>
      <th>Posted by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @toys.each do |toy| %>
      <tr>
        <td><%= toy.name %></td>
        <td><%= toy.description %></td>
        <td><%= toy.date_posted %></td>
        <td><%= toy.posted_by %></td>
        <td><%= link_to 'Show', toy %></td>
        <td><%= link_to 'Edit', edit_toy_path(toy) %></td>
        <td><%= link_to 'Destroy', toy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Toy', new_toy_path %>

app/views/toys/new.html.erb
<h1>New Toy</h1>

<%= render 'form', toy: @toy %>

<%= link_to 'Back', toys_path %>

app/views/toys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @toy.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @toy.description %>
</p>

<p>
  <strong>Date posted:</strong>
  <%= @toy.date_posted %>
</p>

<p>
  <strong>Posted by:</strong>
  <%= @toy.posted_by %>
</p>

<%= link_to 'Edit', edit_toy_path(@toy) %> |
<%= link_to 'Back', toys_path %>